name: Binary cache
on:
  push:
    branches:
      - main

  workflow_run:
    workflows:
      - update
    types:
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  populate:
    name: Build and push binary cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v24
      - name: Setup Cachix
        uses: cachix/cachix-action@v13
        with:
          name: nocargo
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: '(-source$|\.tar\.gz)'

      - name: Build cached crates
        run: nix build .#cache --show-trace --no-update-lock-file
