name: CI
on:
  pull_request:
  push:

  workflow_run:
    workflows:
      - update
    types:
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  flake-check:
    name: Flake check (locked)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v24
      - run: nix flake check --show-trace --no-update-lock-file
